version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: express_server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - STATIC_CONTENT_URL=/uploads/
      - SESSION_SECRET=secret

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://localhost
