@startuml
title User Login Sequence Diagram

actor User
participant "Frontend Server" as frontend
participant "Backend Server" as backend
database "Database" as DB

User -> frontend: GET /login
frontend -> User: Send Login Form
User -> backend: POST /api/auth/login with Credentials

backend -> backend: Validate data
alt Data is Valid
    backend -> DB: Query User by email
    DB -> backend: Fetch user data
    backend -> backend: Validate password
alt Password Matches
    backend -> User: Send Session Cookie and redirect to Home
    User -> frontend: GET / with Homepage
    frontend -> User: Send homepage
    else Password Does Not Match or User does not exist
        DB -> backend: Constraint error
        backend -> User: Send Error Message
end
    else Invalid data 
       backend -> User: Return Validation Error (Invalid email/format)
end

@enduml
