@startuml
title User Registration Sequence Diagram

actor User
participant "Frontend Server" as Frontend
participant "Backend Server" as Backend
database "Database" as DB

User -> Frontend: Open Registration Page
Frontend -> User: Send Registration Form

User -> Backend: POST /api/register with Form Data
Backend --> Backend: Validate data
alt Validation Error
    Backend -> User: Return Error message
else Valid Data
    Backend -> DB: Insert New User
    alt New User
        DB --> Backend: Insert Success
        Backend -> User: Return Success Response with session
        Backend -> User: Send email with confirmation
        User -> Frontend: GET / with Homepage
        Frontend -> User: Send Homepage
    else User Insertion Error
        DB --> Backend: Error
        Backend --> User: Return Error Message
    end
end

@enduml
